const DATA=window.WAYNE_DATA;const $=id=>document.getElementById(id);const norm=t=>(t||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');const fmt=n=>Number(n).toLocaleString('pt-BR');let current=DATA.areas[1];let saved=[];
function find(q){q=norm(q);if(!q)return DATA.areas[1];let ranked=DATA.areas.map(a=>{let m=0;a.keywords.forEach(k=>{if(q.includes(norm(k)))m+=30});a.skills.forEach(s=>{if(q.includes(norm(s)))m+=10});return{...a,match:m}}).sort((a,b)=>b.match-a.match);return ranked[0].match?ranked[0]:DATA.areas[0]}
function drawLine(id,vals,color){let c=$(id),x=c.getContext('2d'),w=c.width=c.clientWidth*devicePixelRatio,h=c.height=c.clientHeight*devicePixelRatio;x.clearRect(0,0,w,h);x.strokeStyle=color;x.lineWidth=4*devicePixelRatio;x.shadowBlur=14*devicePixelRatio;x.shadowColor=color;x.beginPath();vals.forEach((v,i)=>{let px=i/(vals.length-1)*w,py=h-(v/100*h*.8)-h*.1;i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}
function drawDonut(){let c=$('donut'),x=c.getContext('2d'),w=c.width=c.clientWidth*devicePixelRatio,h=c.height=220*devicePixelRatio,cx=w/2,cy=h/2,r=Math.min(w,h)*.32;let parts=[32,21,18,12,17],cols=['#1588ff','#8b38ff','#ff32d2','#ffd36d','#22d66e'],st=-Math.PI/2;x.clearRect(0,0,w,h);parts.forEach((p,i)=>{let en=st+p/100*Math.PI*2;x.beginPath();x.strokeStyle=cols[i];x.lineWidth=25*devicePixelRatio;x.arc(cx,cy,r,st,en);x.stroke();st=en});x.fillStyle='#fff';x.font=`${16*devicePixelRatio}px Arial`;x.textAlign='center';x.fillText('Demanda',cx,cy);x.fillText('100%',cx,cy+22*devicePixelRatio)}
function rand(n=12){return Array.from({length:n},()=>35+Math.random()*55)}
function update(a){current=a;$('score').textContent=a.score;$('sideScore').textContent=a.score;$('kpiCourses').textContent=fmt(9000+a.courses.length*125+a.courses_total);$('kpiProviders').textContent=a.courses.length+3}
function run(q){let a=find(q||$('query').value);update(a);$('result').classList.remove('hidden');$('area').textContent=a.name;$('summary').textContent=a.summary;$('skills').innerHTML=a.skills.map(s=>`<span class="tag">${s}</span>`).join('');$('roles').innerHTML=a.roles.map(s=>`<span class="tag">${s}</span>`).join('');$('courses').innerHTML='<div class="courseGrid">'+a.courses.map(c=>`<div class="course"><button class="save" data-title="${c.title}">☆</button><h3>${c.title}</h3><p>${c.provider} • ${c.type} • ${c.level}</p><a href="${c.url}" target="_blank">Acessar ↗</a></div>`).join('')+'</div>';document.querySelectorAll('.save').forEach(b=>b.onclick=()=>{saved.push(b.dataset.title);renderSaved();b.textContent='★'});drawLine('line',rand(),'#8b38ff');drawLine('spark',rand(8),'#bb6cff');drawDonut();setTimeout(()=>$('result').scrollIntoView({behavior:'smooth'}),60)}
function panels(view){['home','market','saved'].forEach(v=>$(v).classList.add('hidden'));if(view==='home')$('home').classList.remove('hidden');if(view==='market')$('market').classList.remove('hidden');if(view==='saved')$('saved').classList.remove('hidden');document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n.dataset.view===view))}
function renderSaved(){$('savedList').innerHTML=saved.length?saved.map(s=>`<span class="tag">${s}</span>`).join(''):'Nenhum curso salvo ainda.'}
function init(){$('trends').innerHTML=DATA.trends.map(t=>`<div class="row"><span>${t[0]}</span><span class="grow">+${t[1]}%</span></div>`).join('');$('states').innerHTML=DATA.states.map(s=>`<div class="state"><span>${s[0]}</span><span>${s[1]}%</span><div class="bar" style="grid-column:1/-1"><div class="fill" style="width:${s[1]*3}%"></div></div></div>`).join('');$('marketCards').innerHTML=DATA.areas.map(a=>`<div class="marketCard" data-q="${a.name}"><span>${a.name}</span><strong>${a.courses.length*12+a.score}</strong><p>cursos potenciais • +${a.growth}%</p><div class="bar"><div class="fill" style="width:${a.score}%"></div></div></div>`).join('');document.querySelectorAll('.marketCard').forEach(c=>c.onclick=()=>{panels('home');$('query').value=c.dataset.q;run(c.dataset.q)});$('run').onclick=()=>run();$('query').onkeydown=e=>{if(e.key==='Enter')run()};document.querySelectorAll('.chips button').forEach(b=>b.onclick=()=>{$('query').value=b.dataset.q;run(b.dataset.q)});document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>panels(b.dataset.view));setInterval(()=>{$('today').textContent=fmt(18000+Math.floor(Math.random()*1400));drawLine('spark',rand(8),'#bb6cff')},2500);drawLine('spark',rand(8),'#bb6cff');drawLine('line',rand(),'#8b38ff');drawDonut();update(current)}
document.addEventListener('DOMContentLoaded',init);
