import type { Course } from "../types/Course";

export const courses: Course[] = [
  {
    id: "powerbi-bradesco-001",
    title: "Introdução à Análise de Dados — Power BI",
    provider: "Fundação Bradesco",
    area: "Power BI e Dados",
    level: "Iniciante",
    duration: "5h",
    free: true,
    certificate: true,
    language: "Português",
    description: "Curso introdutório para conhecer análise de dados e visualização com Power BI.",
    url: "https://www.ev.org.br/cursos/introducao-a-analise-de-dados-microsoft-power-bi",
    tags: ["power bi", "dados", "dashboard", "bi", "excel"]
  },
  {
    id: "powerbi-enap-002",
    title: "Power BI para Aprimoramento da Gestão",
    provider: "Escola Virtual GOV / ENAP",
    area: "Power BI e Dados",
    level: "Intermediário",
    duration: "25h",
    free: true,
    certificate: true,
    language: "Português",
    description: "Curso voltado à aplicação do Power BI em gestão, indicadores e tomada de decisão.",
    url: "https://www.escolavirtual.gov.br/curso/840",
    tags: ["power bi", "gestão", "dashboard", "indicadores", "dados"]
  },
  {
    id: "microsoft-learn-powerbi-003",
    title: "Power BI Learning Paths",
    provider: "Microsoft Learn",
    area: "Power BI e Dados",
    level: "Todos",
    duration: "Variável",
    free: true,
    certificate: false,
    language: "Português/Inglês",
    description: "Trilhas oficiais da Microsoft para aprender Power BI, relatórios e modelagem.",
    url: "https://learn.microsoft.com/pt-br/training/powerplatform/power-bi",
    tags: ["power bi", "microsoft", "bi", "data visualization"]
  },
  {
    id: "ia-microsoft-004",
    title: "Fundamentos de IA no Microsoft Learn",
    provider: "Microsoft Learn",
    area: "Inteligência Artificial",
    level: "Iniciante",
    duration: "Variável",
    free: true,
    certificate: false,
    language: "Português/Inglês",
    description: "Conteúdos oficiais para iniciar em inteligência artificial, cloud e serviços de IA.",
    url: "https://learn.microsoft.com/pt-br/training/",
    tags: ["ia", "inteligência artificial", "azure", "machine learning", "microsoft"]
  },
  {
    id: "ia-google-005",
    title: "Google Skillshop — IA e Marketing Digital",
    provider: "Google Skillshop",
    area: "Inteligência Artificial",
    level: "Iniciante",
    duration: "Variável",
    free: true,
    certificate: true,
    language: "Português/Inglês",
    description: "Cursos gratuitos do Google para competências digitais, IA aplicada e produtividade.",
    url: "https://skillshop.withgoogle.com/",
    tags: ["ia", "google", "marketing digital", "produtividade", "automação"]
  },
  {
    id: "datascience-classcentral-006",
    title: "Data Science Courses",
    provider: "Class Central",
    area: "Ciência de Dados",
    level: "Todos",
    duration: "Variável",
    free: true,
    certificate: false,
    language: "Inglês/Português",
    description: "Busca global por cursos de ciência de dados em universidades e plataformas abertas.",
    url: "https://www.classcentral.com/search?q=data%20science",
    tags: ["data science", "dados", "python", "sql", "machine learning"]
  },
  {
    id: "direito-enap-007",
    title: "Proteção de Dados Pessoais",
    provider: "Escola Virtual GOV / ENAP",
    area: "Direito Digital",
    level: "Iniciante",
    duration: "Variável",
    free: true,
    certificate: true,
    language: "Português",
    description: "Curso sobre proteção de dados pessoais, LGPD e boas práticas no setor público.",
    url: "https://www.escolavirtual.gov.br/",
    tags: ["direito", "lgpd", "proteção de dados", "compliance", "jurídico"]
  },
  {
    id: "direito-fgv-008",
    title: "Cursos gratuitos em Direito",
    provider: "FGV",
    area: "Direito Digital",
    level: "Variável",
    duration: "Variável",
    free: true,
    certificate: true,
    language: "Português",
    description: "Catálogo de cursos gratuitos da FGV com temas jurídicos, gestão e sociedade.",
    url: "https://educacao-executiva.fgv.br/cursos/gratuitos",
    tags: ["direito", "fgv", "compliance", "contratos", "administração pública"]
  },
  {
    id: "contabilidade-sebrae-009",
    title: "Gestão Financeira",
    provider: "Sebrae",
    area: "Contabilidade e Controladoria",
    level: "Iniciante",
    duration: "10h",
    free: true,
    certificate: true,
    language: "Português",
    description: "Curso para organizar finanças, fluxo de caixa, gestão e controles financeiros.",
    url: "https://loja.sebrae.com.br/cursos/cursos-online",
    tags: ["contabilidade", "financeiro", "fluxo de caixa", "gestão", "controladoria"]
  },
  {
    id: "logistica-enap-010",
    title: "Logística e Compras Públicas",
    provider: "Escola Virtual GOV / ENAP",
    area: "Logística e Operações",
    level: "Intermediário",
    duration: "Variável",
    free: true,
    certificate: true,
    language: "Português",
    description: "Formação em logística, compras públicas, processos e eficiência operacional.",
    url: "https://www.escolavirtual.gov.br/?id_tematica=39",
    tags: ["logística", "compras", "suprimentos", "processos", "operação"]
  },
  {
    id: "arquitetura-autodesk-011",
    title: "Autodesk Learn — AutoCAD e Revit",
    provider: "Autodesk Learn",
    area: "Arquitetura e BIM",
    level: "Todos",
    duration: "Variável",
    free: true,
    certificate: false,
    language: "Inglês/Português",
    description: "Conteúdos oficiais para ferramentas como AutoCAD, Revit e BIM.",
    url: "https://www.autodesk.com/learn",
    tags: ["arquitetura", "autocad", "revit", "bim", "projeto"]
  }
];
